# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

title: "Hannah's Totally Rad 40th Birthday Bash!"
email: me@nathanalderson.com
description: >-
  ðŸŽ‰ 90s High School Dance Party Theme ðŸŽ‰ June 20, 2025 at 6:30pm
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alderson.party"

# Build settings
markdown: kramdown
theme: minima

# GitHub Pages settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
